version: "3.4"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_NAME: QP
      DB_USERNAME: abijith
      DB_PASSWORD: abijiths@005
      JWT_SIGNATURE: secret
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    ports:
    - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: abijiths@005
      MYSQL_DATABASE: QP
      MYSQL_USER: abijith
      MYSQL_PASSWORD: abijiths@005
      DB_HOST: mysql
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
