version: "3.8"

services:
  api:
    build:
      context: .
      target: development
    
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      DB_NAME: QP
      DB_USERNAME: abijith
      DB_PASSWORD: abijiths@005
      JWT_SIGNATURE: secret
    command: npm run dev
    depends_on:
      - mysql  

  mysql:
    image: mysql:latest
    container_name: db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abijiths@005
      MYSQL_DATABASE: QP
      MYSQL_USER: abijith
      MYSQL_PASSWORD: abijiths@005
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
